### ISSUE TITLE
Selling items with custom names

### ISSUE THREAD

**Issue by MXR156** [Nowaha/Shop-by-Conjurate#11]
Hi there, I seem to have found an issue with buying and selling items with custom names. This used to work really well with this plugin prior to Minecraft 1.14.

I have an item with a custom name that I want to be able to buy and sell, however it doesn't recognise the item in your inventory when you go to sell it. It does however recognise the normal item without the custom name.

e.g. COAL_ORE with a custom name "&cWarzone Coal" is in the shop page, however its not seeing that you have that specific item in your inventory when you are holding them. If I get out a normal COAL_ORE and try to sell to the custom named item it will sell only the standard ore.

It seems like it isn't comparing the full itemstack (Names and tags included).

Happy to provide a video if needed?

**Comment by MXR156** [comment]
Thought I would make a video quickly anyway. Here it is if it helps - https://youtu.be/Ii0lfFcTIgM

**Comment by Huskehhh** [comment]
Testing required

**Comment by Ultrasucc** [comment]
Do we have any progress on this? The bug is still present in the latest build (2.1.5 snapshot)

**Comment by Huskehhh** [comment]
Related to #20
