### ISSUE TITLE
Rewrite?

### ISSUE THREAD

**Issue by Huskehhh** [Nowaha/Shop-by-Conjurate#16]
Heyo, just a question.

Do you at all collaborate to rewrite the plugin? This code is very old and ugly. It's super poorly written, and it makes bugfixes a nightmare.

Could also implement MySQL support for shop data storage

Maybe also a config conversion tool to the new version..

Just an idea, if you don't have the time it's also okay! 👍

**Comment by Nowaha** [comment]
I want to help rewrite it. We could assign classes to each other and then we will clean the assigned file up?

**Comment by Huskehhh** [comment]
Awesome!
I was thinking a total overhaul, the current structure is bizarre
I'll create a branch and push some code as to how I think it should be handled

**Comment by Huskehhh** [comment]
https://github.com/Nowaha/Shop-by-Conjurate/tree/v3

**Comment by Nowaha** [comment]
All right

**Comment by Huskehhh** [comment]
I've created a project board with a few broad to-dos.

If you see anything you like, jump on it 👍

**Comment by Nowaha** [comment]
Finally, I have time! School is really becoming demanding, had to close commissions as well. How much have you done so far?

**Comment by Huskehhh** [comment]
Hey mate! Hahaha, yeah. It gets like that! :(

I haven't really done much more than whats in the branch currently.

**Comment by Klawdek** [comment]
I really hope you guys update for 1.15.  A rewrite sounds great.  It is a great plugin and thank you for working on it.  Please keep in the trading feature.  I don't think there are any other plugins that do trading of items.

**Comment by Huskehhh** [comment]
I'm 99% certain that previous version will work with 1.15 :)
Interesting, maybe we will port that to the rewrite then! :D

**Comment by TheRobLP** [comment]
Hey guys. Firstly, I just wanna confirm real quick that the current version of Conjurate-Shop is working just fine on 1.15. Secondly, is the rewrite still going on? Thirdly...: Hi

**Comment by Huskehhh** [comment]
Hey mate. Yeah, rewrite is still in progress. Things are busy near the end of year with christmas and what not. Probably wont see a workable build for a while :)

**Comment by Klawdek** [comment]
I think the addition of a sell all feature that sells all of a specific item rather than having to click to get a number.  It would be convenient for those who want to sell all of something.  Also would be nice if such a feature did not sell items of the type specified if they have been customized.  To explain I was on a server and used their shop to sell all my redstone.  They also used redstone as a special item with custom name and lore.  And the shop also took the special item :(

**Comment by Klawdek** [comment]
Is the rewrite still happening?

**Comment by Klawdek** [comment]
😢

**Comment by Huskehhh** [comment]
I've since found some time for this (yay. holidays!) and will be rewriting it entirely over the coming week or so. 

Hoping to have a stable build out by next Friday (6th)

**Comment by Klawdek** [comment]
YEAH  😍

**Comment by Huskehhh** [comment]
Would really love some beta testers!
Have nearly finished. Contact on Discord: husK#1791

**Comment by Klawdek** [comment]
I would be willing to do some testing.

**Comment by Huskehhh** [comment]
> 
> 
> I would be willing to do some testing.

Are you able to add me on discord?

**Comment by Klawdek** [comment]
Ok I sent a friend request.   My public server is still on 1.15.2 however I can set up a local server for whatever version we want to test.  I will be upgrading my public server soon as 1.16.4 is probably the last one for 16.
