### ISSUE TITLE
Console error when trying to sell item

### ISSUE THREAD

**Issue by Klawdek** [Nowaha/Shop-by-Conjurate#21]
I am using Shop version 2.1.5-SNAPSHOT (March 29 build #6) with git-Paper-146 (MC: 1.15.2)  whenever somone clicks on an item on a page for selling I get the following error:  https://pastebin.com/4Gj9xMdF  the page that produced that error is:  https://pastebin.com/Nhtj1dpx  it happens on all pages that have sell items when trying to click on the item to sell.

I have recently upgraded my server from 1.14.4 to 1.15.2 and these files were original created for 1.14.4

**Comment by Huskehhh** [comment]
ive just pushed a (potential) fix?

i havent had a chance to test, ill try and test tomorrow 👍

**Comment by Klawdek** [comment]
I just put the new version up on my server and it seems to be working when I tested it.  Now we will see what the players say.  Thank you for the quick response.  I am glad you guys are still working on this.  It is a great plugin and I hope the rewrite is still happening.

**Comment by Huskehhh** [comment]
There's a bug in the older versions processing of quantities. I suggest updating
