### ISSUE TITLE
Sell function ignoring NBT data.

### ISSUE THREAD

**Issue by Vyrgax** [Nowaha/Shop-by-Conjurate#24]
The sell function in the shop ignores data such as name, lore, and custommodeldata, and subtracts the amount of sold items of from other similar items as well:

Let's say you want to sell 3 `Iron Ingot `s with the name `Apple`. 
You also have 6 `Iron Ingot`s with the name `Banana`,
as well as 9 `Iron Ingot`s with the name `Pear`.

If you'd sell 3 of the "Apple" iron ingots, the shop takes 3 of the apples, 3 of the bananas, and 3 of the pears as well. You'd then have 0 apples, 3 bananas, and 6 pears.

This basically renders the plugin broken.

**Comment by Vyrgax** [comment]
I'm using 1.14.4 (paper), and the latest snapshot (Shop-by-Conjurate-2.1.5-SNAPSHOT build 10)

**Comment by Huskehhh** [comment]
I've now pushed a commit that should address this. I apologise for the oversight on my behalf when I changed the selling logic.
