### ISSUE TITLE
Sell function bug when selling more than 64

### ISSUE THREAD

**Issue by Vyrgax** [Nowaha/Shop-by-Conjurate#25]
In the latest build (2.1.5 #1), when selling 64 items whilst having more than 64 in your inventory, the shop will take everything from that item.

Let's say you have 2x 64 `Apple`s and an additional 12 apples.
You then open the sell function in the shop, click +64, and then sell 64 apples.
Normally it would take 64 apples from your inventory, but now it takes all apples.

I do have to thank you for fixing the item data selling bug, thank you and keep up the great work!

**Comment by Huskehhh** [comment]
Hey mate. Can I get some more information? Can you see if it works with build 2? If not can I get your configuration?
I've just given it a go and it seemed to work fine :)

**Comment by Vyrgax** [comment]
It does work with build 2, thank you!

**Comment by Vyrgax** [comment]
Nevermind, I've noticed that it still takes the wrong amounts.
In this zip I've added the shop's config file as well as a video

[Archive.zip](https://github.com/Nowaha/Shop-by-Conjurate/files/4492619/Archive.zip)

**Comment by Huskehhh** [comment]
Thanks for the information. I'll look into it now

**Comment by Huskehhh** [comment]
Hey mate. I've just done some testing using your config and replicated your steps and have seemingly patched this.

Please confirm, build 3

**Comment by Vyrgax** [comment]
Build 3 seems to have fixed it, thank you for your quick and wonderful work!
