### ISSUE TITLE
Players must now have exact amount specified  if they have less rather than just taking what they have it errors

### ISSUE THREAD

**Issue by Klawdek** [Nowaha/Shop-by-Conjurate#27]
I just upgraded from an older version of version 2.1.5-SNAPSHOT to the latest version of 2.1.5  I think it was build #3 and now if a player has less than what they specified in the gui it gives them an error.  Before it would just take what they have.  This is inconvenient as the players cant just click 64 5 times when they have 4 1/2 stacks.  It should take what they have if they specify an amount greater than what they have.

**Comment by Huskehhh** [comment]
Just pushed a fix 👍
