### ISSUE TITLE
[Question] Buy/Sell GUI

### ISSUE THREAD

**Issue by TheRobLP** [Nowaha/Shop-by-Conjurate#35]
Hello. I would like to know where the lines of code handling the Buy/Sell GUI´s are located. I need to re-program the plugin so that the Buy/sell GUI is on one page (or there will be a new GUI asking if a user wants to buy/sell an item) to fit the special needs of my server. Sadly Im not that good, so I can´t find the right file.

**Comment by Huskehhh** [comment]
Hey mate!
You're probably best looking around [here](https://github.com/Nowaha/Shop-by-Conjurate/blob/a0cd1c3fc19fff1a0cb520aa1682ac4f2cb5aeca/src/main/java/conj/shop/events/listeners/Shop.java#L522)..

It's a bit of a tricky one cause this codebase is an absolute mess. I'd actually advise not using this plugin at all.
