### ISSUE TITLE
Development build site seems to be down

### ISSUE THREAD

**Issue by Vyrgax** [Nowaha/Shop-by-Conjurate#36]
https://ci.husk.pro/job/Shop-By-Conjurate/
The link given on the spigot page for the development site doesn't seem to work anymore.
Might be the host and something you cant do anything about, but just leaving this here to be sure.

**Comment by Vyrgax** [comment]
The site still isn't up, and the connection is insecure.

**Comment by Huskehhh** [comment]
I've dropped my Jenkins CI entirely (which is where they were hosted) ->
While I HEAVILY avoid using this project, due to it's rats nest of a codebase, you can find the last builds through 'Actions'
https://github.com/Nowaha/Shop-by-Conjurate/actions/runs/144231567
