### ISSUE TITLE
everyone see what im typing

### ISSUE THREAD

**Issue by ghost** [Nowaha/Shop-by-Conjurate#4]
when im change price etc.
i have to type in chat and everyone able to see that

i don't know that this is was done on purpose or not

**Comment by ghost** [comment]
(version v2.1.1)

**Comment by Huskehhh** [comment]
Hey @pumegaming! Can you try this build out for me?
https://ci.husk.pro/job/Shop-By-Conjurate/20/artifact/target/Shop-by-Conjurate-2.1.3-SNAPSHOT.jar
See if you have the same issues. Cheers.

**Comment by ghost** [comment]
yes, im still have the same issues with your build.

**Comment by Huskehhh** [comment]
I have been unable to replicate the issue. It doesn't print to chat at all, nothing in console either.

**Comment by ghost** [comment]
![javaw_BQK1CEtGx5](https://user-images.githubusercontent.com/30237794/63098723-ae817080-bf9d-11e9-9ec2-5dac8dfc53cc.png)
here my plugin in case it might help you

i would try eplicate the issue in local server if i have time.

**Comment by Huskehhh** [comment]
That would be awesome. Please be sure to download the latest build from
https://ci.husk.pro/job/Shop-By-Conjurate/lastSuccessfulBuild/artifact/target/Shop-by-Conjurate-2.1.3-SNAPSHOT.jar

Thanks for the issue report 👍

**Comment by MXR156** [comment]
I had a read of this issue yesterday, and thought I would add some info as I have the same issue. I believe it is becuase you have Essentials Chat plugin running. It overrides the player chat cancel. I have the same issue with Delux Chat.

**Comment by Huskehhh** [comment]
> 
> 
> I had a read of this issue yesterday, and thought I would add some info as I have the same issue. I believe it is becuase you have Essentials Chat plugin running. It overrides the player chat cancel. I have the same issue with Delux Chat.

even on the new build?

**Comment by MXR156** [comment]
I am using build 2.1.4-SNAPSHOT. I did a test myself and disabled DeluxeChat and you cant see the chat anymore. I am pretty sure it's the way the chat plugins re-format the chat text. It's not an issue for me as I have a dev server so I can reload the configs for new shops. But that's what I have found from my research.
