### ISSUE TITLE
Command Cost doesn't work.

### ISSUE THREAD

**Issue by PrinceOfIonia** [Nowaha/Shop-by-Conjurate#6]
Hello, so I have encountered a pretty nasty bug, first I'll tell you what I'm running.

The latest version of Spigot on Minecraft 1.14.4.

The latest version of this plugin that I can download on Spigot. (I downloaded the updated one for MC 1.1.4)

No other GUI shop based plugin installed.

So here's the bug. If you give an item the 'command' function, you are able to select a cost. Lets say I set the cost of my item to $15, if I have under $15 it will not let me buy the item, however if I have over $15 I am able to buy the item BUT, it will not subtract any money from your balance, meaning you can buy an infinite amount of that item as long as you have the money to buy the item once. The regular Buy/Sell functions seem to work normal and are not affected by this. When this bug happens, I do not get any error messages in my console.

Let me know if you need any more info, thanks!

**Comment by Huskehhh** [comment]
Hey there mate. I just pushed a change that should fix this.
Would appreciate if you could test!

https://ci.husk.pro/job/Shop-By-Conjurate/lastSuccessfulBuild/artifact/target/Shop-by-Conjurate-2.1.3-SNAPSHOT.jar

**Comment by PrinceOfIonia** [comment]
Thanks for the quick response! This new version seems to fix the bug, thanks a lot!
