### ISSUE TITLE
sign dont work

### ISSUE THREAD

**Issue by ghost** [Nowaha/Shop-by-Conjurate#7]
I've followed the instruction on the wiki.
But when I right-click at the sign it doesn't do anything.
(Name of the sign have changed to [Sign] after I place it)
I've all the perm.
Conjurate-2.1.3

**Comment by Huskehhh** [comment]
I'm having trouble replicating this issue. I tried on my test server and didn't have any issue at all.
Could potentially be a conflicting plugin? Not sure.

**Comment by ghost** [comment]
hmmmm
yeah...
it might happen because of the conflicting plugin again
