### ISSUE TITLE
Some people have issues with selling in 1.14.4

### ISSUE THREAD

**Issue by Nowaha** [Nowaha/Shop-by-Conjurate#8]
Read my reviews. Is this fixed in the newer builds or is this still an issue?

@Huskehhh

**Comment by Huskehhh** [comment]
fixed in https://github.com/Huskehhh/Shop-by-Conjurate/commit/e3e094ed39cdd6862aae8255e5244921f21987ff

**Comment by Nowaha** [comment]
Does the latest build https://ci.husk.pro/job/Shop-By-Conjurate/ also work with 1.14? The api-version is set to 1.13

**Comment by Huskehhh** [comment]
> Does the latest build https://ci.husk.pro/job/Shop-By-Conjurate/ also work with 1.14? The api-version is set to 1.13

Yes, just makes it backwards compatible
