### ISSUE TITLE
Open command = balance?

### ISSUE THREAD

**Issue by Nowaha** [Nowaha/Shop-by-Conjurate#9]
I updated to the new shop version..

if i click on a item with shop page open >name< %player% as command i get this message:

https://puu.sh/EeXFh/066adaeb80.png

- FunnysBanana

What could be the cause?

**Comment by Huskehhh** [comment]
Issue is fixed. I also don't appreciate you uploading my code to your Spigot resource page without permission or without credit.

**Comment by Nowaha** [comment]
Sure, understand that. I added credit to the page. If you want me to just remove it instead that's fine.

**Comment by Nowaha** [comment]
If you want me to credit you in a different way lmk :)

**Comment by Huskehhh** [comment]
I was wrong. Issue should be fixed in latest build! :)
